# Generated by Django 5.2.17 on 2026-09-29 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0007_customerprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Paid', 'Paid'), ('Failed', 'Failed'), ('Not Required', 'Not Required')], default='Pending', max_length=20),
        ),
    ]
